# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 17:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20150626_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='date'),
        ),
    ]
