# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20150626_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
