# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20150908_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmasa',
            name='references',
            field=models.TextField(blank=True, help_text=b'Links to reporter etc.'),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='year',
            field=models.IntegerField(choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016),
        ),
    ]
