# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20170321_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmasa',
            name='cve',
            field=models.CharField(help_text=b'Space separated list of related CVE entries, enter CVE-2017- in case none is assigned yet', max_length=200),
        ),
    ]
