# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 17:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_auto_20170329_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmasa',
            name='commits',
            field=models.TextField(help_text='Space separated list of commits, commits for different branches should be placed on separate line prefixed with version prefix. For example: 3.5: 01d35b3558e47fba947719857bd71f6fd9e5dce8'),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='cve',
            field=models.CharField(help_text='Space separated list of related CVE entries, enter CVE-2017- in case none is assigned yet', max_length=200),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='cwe',
            field=models.CharField(default='661', help_text='Space separated list of CWE classifications', max_length=200),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='draft',
            field=models.BooleanField(default=True, help_text='Draft entries are not shown in website listings'),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='references',
            field=models.TextField(blank=True, help_text='Links to reporter etc.'),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='sequence',
            field=models.IntegerField(help_text='Sequence number of PMASA in given year'),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='solution',
            field=models.TextField(default='Upgrade to phpMyAdmin ? or newer or apply patch listed below.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='updated',
            field=models.DateTimeField(blank=True, help_text='Set this in case of major update to the entry', null=True),
        ),
        migrations.AlterField(
            model_name='pmasa',
            name='year',
            field=models.IntegerField(choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
    ]
