# Generated by Django 3.2.25 on 2024-06-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_alter_pmasa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmasa',
            name='year',
            field=models.IntegerField(choices=[(2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024),
        ),
    ]
