# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='sha256',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sha256',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
