# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20161124_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='snapshot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
