# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_release_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
