# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_theme_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
