<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="page_title">Improve</py:def>

<div py:match="content" id="body">

<h2>Improve phpMyAdmin</h2>

<p>
As a free software project, phpMyAdmin is very open to your contributions. You don't
need developer skills to help, there are several non-coding ways to get involved
in a project (code is welcome too, of course!).
</p>

<p>Ways in which you can contribute:</p>
<ul>
  <li><a href="#devel">program</a> new features,</li>
  <li>report <a href="http://sourceforge.net/tracker/?atid=377408&amp;group_id=23067">bugs</a> (errors in the program),</li>
  <li>debug existing features,</li>

  <li>improve documentation or the <a href="http://wiki.phpmyadmin.net/">wiki</a>,</li>
  <li><a href="#translate">translate phpMyAdmin</a> to your own language,</li>
  <li><a href="#translate">translate the documentation</a>,</li>
  <li>help other users on <a href="https://sourceforge.net/forum/?group_id=23067">forums</a>,</li>

  <li>distribute phpMyAdmin,</li>
  <li><a href="${base_url}donate.${file_ext}">donate money</a> to the project,</li>
</ul>

<p>As you can see, everyone can help.</p>

<h2><a id="devel"></a>Developing</h2>

<p>
phpMyAdmin is (as the name says) written in PHP and uses MySQL. Besides this,
we also need people skilled in HTML, JavaScript and CSS, as these are parts
which make our user interface. You don't have to be expert in all these areas
- even knowing only one of them, you can still provide substantial help in
creating or debugging some features.
</p>

<p>
For storing our code we use <a href="http://git-scm.com/">Git</a>.
If you don't know it, you can get some basic facts in <a
href="http://en.wikipedia.org/wiki/Git_software">Wikipedia</a> or
reference in the comprehensive book <a href="http://progit.org/">Pro Git</a>.
</p>

<h3>Contributing code</h3>
<p>
Once you have coded an improvement and you are ready to submit it to us,
please use our <a
href="https://sourceforge.net/tracker/?group_id=23067&amp;atid=377410">patch
tracker</a>, where developers will pick up your contributions or guide you
through improving the patch.
</p>

<h3>Simple tasks to start</h3>
<p>
If you are looking for some simple task where you can start, check out
our wiki page with <a href="http://wiki.phpmyadmin.net/pma/Tasks_for_junior_developers">junior
jobs</a> where you can find some tips where to look.
</p>

<h3>Source Code Repository</h3>
<xi:include href="_gitdl.tpl" />

<p>
You want to start with the <code>phpmyadmin</code> repository. 
Full list of repositories include:
</p>

<dl class="cvslist">
<dt>phpmyadmin</dt><dd>phpMyAdmin code.</dd>
<dt>website</dt><dd>Website code.</dd>
<dt>themes</dt><dd>Custom themes.</dd>
<dt>data</dt><dd>Various project related data (such as logos, T-shirt graphics, etc.).</dd>
<dt>history</dt><dd>Some historical documents (old changelogs or website).</dd>
<dt>planet</dt><dd><a href="http://planet.phpmyadmin.net/">Planet phpMyAdmin</a> configuration.</dd>
<dt>localized_docs</dt><dd>Localized documentation.</dd>
</dl>

<p>
Examples of how to checkout phpMyAdmin code:
</p>

<pre>
#  Latest development version:
git clone git://phpmyadmin.git.sourceforge.net/gitroot/phpmyadmin/phpmyadmin
</pre>

<h3>Repository Statistics</h3>
<p>Several statistics about the repository are available:</p>
<ul>
<li><a href="http://cia.vc/stats/project/phpmyadmin/">CIA.vc</a></li>
<li><a href="http://www.ohloh.net/projects/phpmyadmin">Ohloh</a></li>
<li><a href="https://sourceforge.net/project/stats/detail.php?group_id=23067&amp;ugn=phpmyadmin&amp;type=git">SourceForge.net</a></li>
</ul>

<h3>Coding Standards</h3>
<p>
Standards should be obeyed in all cases when possible. Generated content
should be valid XHTML 1.0 and CSS. PHP code should match <a
href="http://pear.php.net/manual/en/standards.php">PEAR Coding Standards</a>
and documented using <a href="http://www.phpdoc.org/">phpDocumentator</a>.
More information about coding is available on <a href="http://wiki.phpmyadmin.net/pma/Devel:Coding_guidelines">
our wiki</a>.
</p>

<h3>Developer Documentation</h3>

<p>More documentation can be found in the following places:</p>
<ul>
<li><a href="http://wiki.phpmyadmin.net/pma/Devel:Main">Developers wiki</a></li>
<li><a href="http://www.phpmyadmin.net/phpdoc/">phpMyAdmin's internals
(autogenerated via phpDocumentator)</a></li>
</ul>

<h2><a id="translate"></a>Translating</h2>

<p>
For localization, phpMyAdmin uses Gettext, you can find po files for each
translation in <code>po</code> directory in phpMyAdmin sources. You can
translate them using usual tools for handling Gettext translations or use our
<a href="https://l10n.cihar.com/projects/phpmyadmin/">translation server</a>.
More information about translating can be found in
<a href="http://www.phpmyadmin.net/documentation/#faq7_2">FAQ 7.2</a>. The more
detailed documentation can be found on our <a href="http://wiki.phpmyadmin.net/pma/Translating">wiki</a>.
</p>

<p>
Documentation is being translated using po4a and gettext (see <a
href="${base_url}docs.${file_ext}">documentation</a> for existing
translations). To start, checkout <code><a
href="http://phpmyadmin.git.sourceforge.net/git/gitweb.cgi?p=phpmyadmin/localized_docs;a=tree;f=po">localized_docs/po</a></code> from Git, or
just go to <a href="https://l10n.cihar.com/projects/pmadoc/">translation
server</a> and translate it online. If your language is missing, just contact
<a href="mailto:michal@cihar.com">Michal Čihař</a>, he will add it.  If you
prefer to translate directly the po files, please put updated ones into our <a
href="https://sourceforge.net/tracker/?group_id=23067&amp;atid=387645">translation
tracker</a>.
</p>

</div>

<xi:include href="_page.tpl" />
</html>
